### ISSUE TITLE
pytest fail

### ISSUE THREAD

**Issue by teemu-ruokolainen** [AaltoPML/VAI-Lab#75]
#### Description
Pytests fail for latest main branch version.

#### To reproduce

```
python3 -m venv venv && source venv/bin/activate
python3 -m pip install -U pip
python3 -m pip install .
pytest .
```

#### Error messages
=============================================================================================================================== ERRORS ===============================================================================================================================
____________________________________________________________________________________________________ ERROR collecting src/vai_lab/Core/tests/test_vai_lab_core.py ____________________________________________________________________________________________________
ImportError while importing test module '/u/92/ruokolt1/unix/rse/VAI-labs/src/vai_lab/Core/tests/test_vai_lab_core.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
src/vai_lab/__init__.py:1: in <module>
    from .Core import Core
src/vai_lab/Core/__init__.py:7: in <module>
    from .vai_lab_core import Core
src/vai_lab/Core/vai_lab_core.py:3: in <module>
    from vai_lab.GUI.GUI_core import GUI
src/vai_lab/GUI/GUI_core.py:3: in <module>
    from vai_lab._types import DataInterface, PluginSpecsInterface, DictT
src/vai_lab/_types.py:3: in <module>
    from tkinter.font import Font
E   ModuleNotFoundError: No module named 'tkinter'
_________________________________________________________________________________________________________ ERROR collecting src/vai_lab/tests/test_launch.py __________________________________________________________________________________________________________
ImportError while importing test module '/u/92/ruokolt1/unix/rse/VAI-labs/src/vai_lab/tests/test_launch.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
src/vai_lab/__init__.py:1: in <module>
    from .Core import Core
src/vai_lab/Core/__init__.py:7: in <module>
    from .vai_lab_core import Core
src/vai_lab/Core/vai_lab_core.py:3: in <module>
    from vai_lab.GUI.GUI_core import GUI
src/vai_lab/GUI/GUI_core.py:3: in <module>
    from vai_lab._types import DataInterface, PluginSpecsInterface, DictT
src/vai_lab/_types.py:3: in <module>
    from tkinter.font import Font
E   ModuleNotFoundError: No module named 'tkinter'
====================================================================================================================== short test summary info =======================================================================================================================
ERROR src/vai_lab/Core/tests/test_vai_lab_core.py
ERROR src/vai_lab/tests/test_launch.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2 errors in 0.39s

**Comment by cam586** [comment]
Fixed in #73
