### ISSUE TITLE
Fix examples path in README.md/docs

### ISSUE THREAD

**Issue by teemu-ruokolainen** [AaltoPML/VAI-Lab#84]
Using CLI, the path to examples should be
 
`vai_lab --file ./src/vai_lab/examples/xml_files/user_feedback_demo.xml`

instead of 

`vai_lab --file ./examples/xml_files/user_feedback_demo.xml`

which works for the "from code" as the examples are part of source and included in the site-packages.

**Comment by cam586** [comment]
Resolved  in #86

**Comment by cam586** [comment]
Re-fixed in #87
